In [8]:
import pandas as pd
import cv2 as cv
import os

Step 1: Creating a dataframe with im_names and labels

In [42]:
# Creating the Master DF
train_dir = '/Users/adharshv/Documents/Career/portfolio/Plant_Disease/New Plant Diseases Dataset(Augmented)/train/'
dir_ls = os.listdir(train_dir)
df = pd.DataFrame({'im_name':[],'plant_type':[],'status':[]})

for dir in dir_ls:
    temp_df = pd.DataFrame()
    dir_name = dir.split('_',1)
    plant_name = dir_name[0]
    status = dir_name[1].replace('_','')
    files = os.listdir(train_dir+dir)
    temp_df['im_name'] = files
    temp_df['plant_type'] = plant_name
    temp_df['status'] = status
    df = pd.concat([df,temp_df],axis=0,ignore_index=True)
    # print(plant_name)
    # print(status)
    # print(files)
    
df

                                                 im_name  plant_type   status
0      0370bc9b-c0c8-49b5-b999-c44323c45216___RS_HL 2...  Strawberry  healthy
1      741e834f-a63a-4efd-b961-d5f7e047abdc___RS_HL 2...  Strawberry  healthy
2      b8e9ed27-8e37-4214-9206-f8c0ef21cf4d___RS_HL 4...  Strawberry  healthy
3      ac5bf646-1586-4766-9583-ef6eb8f7b4a6___RS_HL 4...  Strawberry  healthy
4      d07e9834-ac76-4390-9463-cbef9d0269da___RS_HL 1...  Strawberry  healthy
...                                                  ...         ...      ...
70290  c127579f-9800-44fe-88fd-40eceef2520c___RS_HL 6...     Soybean  healthy
70291  31800ff8-157b-4690-9200-1e86c7c605b2___RS_HL 7...     Soybean  healthy
70292  9898aa61-2804-4b30-a52c-bdf95cbdd013___RS_HL 4...     Soybean  healthy
70293  df807f13-078b-4a6a-9c23-e43e540ecdc2___RS_HL 5...     Soybean  healthy
70294  c7f4b7b2-b13c-476e-a936-c91ce39749a3___RS_HL 6...     Soybean  healthy

[70295 rows x 3 columns]

In [41]:
df[df['plant_type']=='Strawberry']

,im_name,plant_type,status
0,0370bc9b-c0c8-49b5-b999-c44323c45216___RS_HL 2...,Strawberry,healthy
1,741e834f-a63a-4efd-b961-d5f7e047abdc___RS_HL 2...,Strawberry,healthy
2,b8e9ed27-8e37-4214-9206-f8c0ef21cf4d___RS_HL 4...,Strawberry,healthy
3,ac5bf646-1586-4766-9583-ef6eb8f7b4a6___RS_HL 4...,Strawberry,healthy
4,d07e9834-ac76-4390-9463-cbef9d0269da___RS_HL 1...,Strawberry,healthy
...,...,...,...
66444,15f02e8e-503c-4e14-8728-51dc3d4a2f10___RS_L.Sc...,Strawberry,Leafscorch
66445,b6b2dc65-b606-4cde-824e-dcba8d8a5457___RS_L.Sc...,Strawberry,Leafscorch
66446,5b19c65d-67a1-439e-b699-bb41ed610fba___RS_L.Sc...,Strawberry,Leafscorch
66447,6a459155-1892-46e5-bac6-c15bf352fc1c___RS_L.Sc...,Strawberry,Leafscorch
66448,47a98502-4839-44cd-b855-fd4d3f9f1810___RS_L.Sc...,Strawberry,Leafscorch

In [ ]:
# Creating independent plant dfs

def create_plant_df(data,plant_type):
    return data[data['plant_type']==plant_type]